# Generated by Django 4.0.3 on 2022-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Shirts',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='shirts',
        ),
    ]
