# Generated by Django 4.0.3 on 2022-05-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shirts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('Shirt', 'Shirts'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes')], max_length=100)),
                ('image', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shirts',
        ),
        migrations.DeleteModel(
            name='Shirts',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
