# Generated by Django 4.0.3 on 2022-05-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
