# Generated by Django 4.0.3 on 2022-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_remove_orderitem_shirts_delete_shirts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes')], max_length=100),
        ),
    ]
