# Generated by Django 4.0.3 on 2022-05-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Shoes', 'Shoes')], max_length=100, null=True),
        ),
    ]
